version: "3"
services:
  website:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/django-blog
    environment:
      - DB_HOST=db
      - DB_NAME=djangoblog
      - DB_USER=aliona
      - DB_PASS=postrges
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - website-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=djangoblog
      - POSTGRES_USER=aliona
      - POSTGRES_PASSWORD=postrges
    ports:
      - "5432:5432"
volumes:
  website-db: