version: "3"
services:
  db:
    image: postgres:13-alpine
    volumes:
      - website-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=djangoblog
      - POSTGRES_USER=aliona
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  website:
    build:
      context: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
#    volumes:
#      - .:/django-blog
    environment:
      - DB_HOST=db
      - DB_NAME=djangoblog
      - DB_USER=aliona
      - DB_PASS=postgres
    depends_on:
      - db

volumes:
  website-db: