# Generated by Django 4.0 on 2022-01-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_suggested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggested',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
