# Generated by Django 4.0 on 2022-03-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_suggested_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggested',
            options={'ordering': ['-created_date'], 'verbose_name': 'Suggested news', 'verbose_name_plural': 'Suggested news'},
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='created on'),
        ),
    ]
